---
- name: Add mongodb.org GPG key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc

- name: Addm mongodb.org APT repo
  ansible.builtin.apt_repository:
    repo: "deb http://mirrors.cloud.tencent.com/mongodb/apt/ubuntu focal/mongodb-org/5.0 multiverse"  # using china mirror, cuz repo.mongodb.org bans russians

- name: Install mongodb server
  ansible.builtin.apt:
    name:
      - mongodb-org

- name: Make sure mongodb python module is installed
  pip:
    name: pymongo

- name: Make sure mongo data directory exists
  ansible.builtin.file:
    name: /var/lib/mongodb
    state: directory
    mode: "0750"
    owner: mongodb
    group: mongodb


- name: Run mongodb server
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: started

- name: Check if mongod auth is already set up
  stat:
    path: /etc/.mongodb-init-done
  register: mongod_setup

- name: Update mongod config file
  when: not mongod_setup.stat.exists
  template:
    src: templates/mongod-first-time.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify:
    - Restart mongod

- name: Create admin user
  when: not mongod_setup.stat.exists
  community.mongodb.mongodb_user:
    login_host: "{{ mongodb_host }}"
    connection_options: ""
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    db: "admin"
    roles: dbAdminAnyDatabase,userAdminAnyDatabase,readWriteAnyDatabase

- name: Mark mongdb init as done
  ansible.builtin.copy:
    dest: /etc/.mongodb-init-done
    content: ""

- name: Update mongod config file
  when: not mongod_setup.stat.exists
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify:
    - Restart mongod

- name: Create ackee user
  community.mongodb.mongodb_user:
    login_host: "{{ mongodb_host }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    connection_options: ""
    update_password: on_create
    name: "{{ ackee_mongodb_user }}"
    password: "{{ ackee_mongodb_password }}"
    db: "{{ ackee_mongodb_database }}"
    roles:
      - db: "{{ ackee_mongodb_database }}"
        role: readWrite

