---
- name: restart network
  ansible.builtin.service:
    name: networking
    state: restarted
  become: yes

- name: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
  become: yes
